alias tf='cd ~/source/ticketfly/'
alias rebasemaster='git fetch; and git rebase origin/master'
alias es='ember s'
alias ets='ember test --server'
alias nom='npm cache clear && rm -rf node_modules && npm install'
alias bom='bower cache clean && rm -rf bower_components && bower install'
alias nombom='npm cache clear && bower cache clean && rm -rf node_modules bower_components && npm install && bower install'
alias ll='ls -al'
